services:
  web:
    image: laravelsail/php82-composer
    container_name: nekoerp_web
    ports:
      - "8000:8000"
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - database
    networks:
      - nekoerp

  database:
    image: mysql:8.0
    container_name: nekoerp_database
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: nekoerp
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - nekoerp

networks:
  nekoerp:
    driver: bridge